### ISSUE TITLE
The error prompt for a wrong password should only pop up 2 to 3 times

### ISSUE THREAD

**Issue by sacredartr** [open-v2x/roadmocker#22]
## Describe the bug

The error prompt for a wrong password should only pop up 2 to 3 times

## Screenshots
<img width="1482" alt="WechatIMG1154" src="https://user-images.githubusercontent.com/56632872/185526002-a45d13dd-c36e-410c-a05a-cee38bdf2b1d.png">

## Desktop (please complete the following information):

- OS: mac
- Browser: chrome
- Version: master

**Comment by AriaAto** [comment]
yes, the question because of the mqtt reconnection. so, i`ll close it when u connect when the wrong message to login
