### ISSUE TITLE
The json of Reporting rsu information needs to be optimized and so on

### ISSUE THREAD

**Issue by sacredartr** [open-v2x/roadmocker#24]
## Describe the bug

1. The json of Reporting rsu information needs to be optimized
2. Heartbeat expiration time needs to be displayed

## Screenshots
<img width="1417" alt="WechatIMG1163" src="https://user-images.githubusercontent.com/56632872/185532411-df16e3f9-41e2-4b13-a478-e2c23d36dfc6.png">

## Desktop (please complete the following information):

- OS: mac
- Browser: chrome
- Version: master

**Comment by wu-wenxiang** [comment]
因为 RSU Esn 不允许减号，后面 edgeview 上添加 RSU 时有验证。
所以，这里是不是应该处理下 client id 的输入交验，让他只允许 RSU Esn 特定字符

**Comment by wu-wenxiang** [comment]
现在默认还是 RSU-xxxx，可以默认去掉这个减号，或者改成下划线

**Comment by wu-wenxiang** [comment]
password 默认也改成 password，和文档里的安装文档里的默认值一致
